import Mathlib

/-!
# Three-mode Gershgorin coercivity certificates

The remaining analytic CvS--prolate bridge is naturally tested on the two fixed
three-dimensional tail spaces generated by modes `(0,4,8)` and `(2,6,10)`.
After normalizing by the prolate defect weights, coercivity of the Weil form can
be certified from six scalar interval bounds per block.

This file proves the real three-variable quadratic-form estimate behind that
certificate.  It contains no assertion about the actual Weil matrix entries.
-/

namespace RiemannCvs.ThreeModeGershgorin

/-- A single real cross term is bounded below by its absolute Gershgorin
contribution. -/
theorem crossTermLower
    (a x y : ℝ) :
    -|a| * (x ^ 2 + y ^ 2) ≤ 2 * a * x * y := by
  by_cases ha : 0 ≤ a
  · rw [abs_of_nonneg ha]
    by_cases hxy : 0 ≤ x * y
    · have hsum : 0 ≤ x ^ 2 + y ^ 2 := by positivity
      have hleft : -a * (x ^ 2 + y ^ 2) ≤ 0 := by
        exact mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr ha) hsum
      have hright : 0 ≤ 2 * a * x * y := by
        positivity
      exact hleft.trans hright
    · have hxy' : x * y < 0 := lt_of_not_ge hxy
      have hsquare : 0 ≤ (x + y) ^ 2 := sq_nonneg _
      nlinarith
  · have ha' : a < 0 := lt_of_not_ge ha
    rw [abs_of_neg ha']
    by_cases hxy : 0 ≤ x * y
    · have hsquare : 0 ≤ (x - y) ^ 2 := sq_nonneg _
      nlinarith
    · have hxy' : x * y < 0 := lt_of_not_ge hxy
      have hsum : 0 ≤ x ^ 2 + y ^ 2 := by positivity
      have hleft : a * (x ^ 2 + y ^ 2) ≤ 0 :=
        mul_nonpos_of_nonpos_of_nonneg (le_of_lt ha') hsum
      have hright : 0 ≤ 2 * a * x * y := by
        have hprod : 0 ≤ a * (x * y) :=
          mul_nonneg_of_nonpos_of_nonpos (le_of_lt ha') (le_of_lt hxy')
        nlinarith
      exact hleft.trans hright

/-- Matching upper bound for a real cross term. -/
theorem crossTermUpper
    (a x y : ℝ) :
    2 * a * x * y ≤ |a| * (x ^ 2 + y ^ 2) := by
  have h := crossTermLower (-a) x y
  rw [abs_neg] at h
  nlinarith

/-- Lower Gershgorin certificate for a symmetric three-mode quadratic form. -/
theorem threeModeLower
    (alpha d0 d1 d2 a01 a02 a12 x0 x1 x2 : ℝ)
    (h0 : alpha + |a01| + |a02| ≤ d0)
    (h1 : alpha + |a01| + |a12| ≤ d1)
    (h2 : alpha + |a02| + |a12| ≤ d2) :
    alpha * (x0 ^ 2 + x1 ^ 2 + x2 ^ 2) ≤
      d0 * x0 ^ 2 + d1 * x1 ^ 2 + d2 * x2 ^ 2 +
        2 * a01 * x0 * x1 +
        2 * a02 * x0 * x2 +
        2 * a12 * x1 * x2 := by
  have h01 := crossTermLower a01 x0 x1
  have h02 := crossTermLower a02 x0 x2
  have h12 := crossTermLower a12 x1 x2
  have hx0 : 0 ≤ x0 ^ 2 := sq_nonneg _
  have hx1 : 0 ≤ x1 ^ 2 := sq_nonneg _
  have hx2 : 0 ≤ x2 ^ 2 := sq_nonneg _
  nlinarith

/-- Upper Gershgorin certificate for a symmetric three-mode quadratic form. -/
theorem threeModeUpper
    (beta d0 d1 d2 a01 a02 a12 x0 x1 x2 : ℝ)
    (h0 : d0 + |a01| + |a02| ≤ beta)
    (h1 : d1 + |a01| + |a12| ≤ beta)
    (h2 : d2 + |a02| + |a12| ≤ beta) :
    d0 * x0 ^ 2 + d1 * x1 ^ 2 + d2 * x2 ^ 2 +
        2 * a01 * x0 * x1 +
        2 * a02 * x0 * x2 +
        2 * a12 * x1 * x2 ≤
      beta * (x0 ^ 2 + x1 ^ 2 + x2 ^ 2) := by
  have h01 := crossTermUpper a01 x0 x1
  have h02 := crossTermUpper a02 x0 x2
  have h12 := crossTermUpper a12 x1 x2
  have hx0 : 0 ≤ x0 ^ 2 := sq_nonneg _
  have hx1 : 0 ≤ x1 ^ 2 := sq_nonneg _
  have hx2 : 0 ≤ x2 ^ 2 := sq_nonneg _
  nlinarith

/-- Two-sided coercivity from row-sum bounds. -/
theorem threeModeCoercivity
    (alpha beta d0 d1 d2 a01 a02 a12 x0 x1 x2 : ℝ)
    (hLower0 : alpha + |a01| + |a02| ≤ d0)
    (hLower1 : alpha + |a01| + |a12| ≤ d1)
    (hLower2 : alpha + |a02| + |a12| ≤ d2)
    (hUpper0 : d0 + |a01| + |a02| ≤ beta)
    (hUpper1 : d1 + |a01| + |a12| ≤ beta)
    (hUpper2 : d2 + |a02| + |a12| ≤ beta) :
    alpha * (x0 ^ 2 + x1 ^ 2 + x2 ^ 2) ≤
        d0 * x0 ^ 2 + d1 * x1 ^ 2 + d2 * x2 ^ 2 +
          2 * a01 * x0 * x1 +
          2 * a02 * x0 * x2 +
          2 * a12 * x1 * x2 ∧
      d0 * x0 ^ 2 + d1 * x1 ^ 2 + d2 * x2 ^ 2 +
          2 * a01 * x0 * x1 +
          2 * a02 * x0 * x2 +
          2 * a12 * x1 * x2 ≤
        beta * (x0 ^ 2 + x1 ^ 2 + x2 ^ 2) := by
  exact ⟨
    threeModeLower alpha d0 d1 d2 a01 a02 a12 x0 x1 x2
      hLower0 hLower1 hLower2,
    threeModeUpper beta d0 d1 d2 a01 a02 a12 x0 x1 x2
      hUpper0 hUpper1 hUpper2
  ⟩

end RiemannCvs.ThreeModeGershgorin
